config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  root :to => redirect('/entrar')
    
  devise_for :professionals, path: "", path_names: { sign_in: 'entrar', sign_out: 'sair', password: 'profissional/senha', confirmation: 'profissional/confirmar', unlock: 'profissional/desbloquear', sign_up: 'profissional/cadastrar' }, controllers: { sessions: 'sessions', registrations: 'devise/professional_registrations', confirmations: 'devise/professional_confirmations' }
  devise_for :customers, path: "", path_names: { sign_in: 'entrar', sign_out: 'sair', password: 'cliente/senha', confirmation: 'cliente/confirmar', unlock: 'cliente/desbloquear' }, controllers: { sessions: 'sessions' }, skip: ['registrations']

  as :customer do

    get "/auth/:provider/callback", :to => "omniauth_callbacks#facebook"
    get '/auth/failure', to: redirect('/')
    
    scope 'cliente' do
      root 'customers#minhas_safiras_por_profissionais', as: :customer_root
      get 'fotos/:token', to: 'photos#index', as: :my_photos
      post 'assign_rewards_to_customer', to: 'rewards#assign_rewards_to_customer', as: :assign_rewards_to_customer
    end
  end

  as :professional do
    
    get "/auth/:provider/callback", :to => "omniauth_callbacks#facebook"
    get '/auth/failure', to: redirect('/')
    
    scope 'profissional' do
      root 'photos#new', as: :professional_root

      resources :sign_up_steps, only: [:index, :show, :update]
      resources :photos, only: [:new, :create, :destroy]
      post 'get_rewards_by_customers_telephone/', to: 'rewards#get_rewards_by_customers_telephone', as: :get_rewards_by_customers_telephone
      post 'notificacao', to: 'notifications#new', as: :new_notification
    end
  end

  get 'retorno-pagamento', to: 'notifications#retorno_pagamento', as: :retorno_pagamento

  mount Sidekiq::Web, at: '/sidekiq'

  get ":slug", to: 'photos#my_site', as: :professionals_site

  # Esta rota TEM que ser a última da listagem, pois
  # seu objetivo é redirecionar o usuário para uma
  # página 404 no caso onde a rota não existe.
  match '*path', via: :all, to: 'static_pages#error_404'
end

app/models/customer.rb
# == Schema Information
#
# Table name: customers
#
#  id                     :integer          not null, primary key
#  nome                   :string(255)
#  email                  :string(255)
#  created_at             :datetime
#  updated_at             :datetime
#  telefone               :string(255)
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  provider               :string(255)
#  uid                    :string(255)
#  oauth_token            :string(255)
#  oauth_expires_at       :datetime
#  avatar_url             :string(255)
#

class Customer < ActiveRecord::Base

  # Foto divulgada - a qual permitiu o cadastro
  attr_accessor :photo_id

  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable,
          :trackable, :validatable
  
  has_many :reward_logs
  has_many :rewards
  has_many :professionals, through: :rewards
  has_many :customer_invitations


  scope :find_by_provider_and_uid, -> (provider, uid) { where("provider = ? AND uid = ?", provider, uid) }

  # Cliente só pode cadastrar se realizou divulgação. Nesse sentido ele é recompensado
  # logo após o cadastro
  # after_create :reward_customer

  # def reward_customer
  #   pId = self.photo_id
  #   Photo.find(pId).customer_invitation.award_rewards(self.id, pId)
  # end

  # def update_schedule
  #   sc = Schedule.find(self.schedule_invitation)
  #   sc.update_attribute(:customer_id, self.id)
  #   self.update_attribute(:telefone, sc.telefone)
  #   # CustomerInvitation.find_by_schedule_id(self.schedule_invitation).delete
  # end

  # def schedules_not_more_than_12_hours_ago
  #   @sc ||= self.schedules.not_more_than_12_hours_ago
  # end
  
  # def can_send_photo?
  #   self.schedules_not_more_than_12_hours_ago.any?
  # end

  # def save_provider_uid(auth)
  #   authData = {
  #                 provider: auth.provider,
  #                 uid: auth.uid,
  #                 oauth_token: auth.credentials.token,
  #                 oauth_expires_at: Time.at(auth.credentials.expires_at)
  #               } 
  #   update_attributes(authData)
  # end

  def facebook
    @facebook ||= Koala::Facebook::API.new(oauth_token)
    block_given? ? yield(@facebook) : @facebook
  rescue Koala::Facebook::APIError => e
    logger.info e.to_s
    nil # or consider a custom null object
  end

  def update_with_omniauth(auth, params)
    self.tap do |o|
      o.update!({
        provider: auth.provider,
        uid: auth.uid,
        oauth_token: auth.credentials.token,
        oauth_expires_at:  Time.at(auth.credentials.expires_at),
        email: auth.info.email,
        avatar_url: auth.info.image,
        nome: auth.extra.raw_info.first_name
      })
    end
  end

  # def gave_fb_permissions?
  #   @gave ||= self.uid.present? &&
  #               self.oauth_expires_in_the_future? &&
  #               self.fb_publish_action_granted?
  # end

  # def oauth_expires_in_the_future?
  #   self.oauth_expires_at.present? && self.oauth_expires_at > Time.zone.now
  # end

  # def fb_publish_action_granted?
  #   self.facebook.get_object("me/permissions").any? do |p|
  #     p['permission'] == 'publish_actions' && p['status'] == 'granted'
  #   end
  # end

  # def get_rewards_by(postedPhotos)
  #   pp = postedPhotos.first
  #   sc = pp.schedule

  #   if sc.recompensa_fornecida
  #     0
  #   else
  #     rw = Reward.find_or_initialize_by(professional_id: sc.professional_id, customer_id: self.id)
  #     rw.total_safiras = rw.total_safiras + sc.price.recompensa_divulgacao
  #     if rw.save
  #       sc.update_attribute(:recompensa_fornecida, true)
  #       sc.price.recompensa_divulgacao
  #     end
  #   end
  # end

  # def find_last_schedule
  #   GetLastScheduleWorker.perform_async(self.email, self.telefone, self.id)
  # end

  # def safiras_somadas
  #   self.rewards.
  #           joins('left outer join professionals on rewards.professional_id = professionals.id').
  #           joins('left outer join statuses on professionals.status_id = statuses.id').
  #           where("statuses.nome in ('testando', 'assinante')").
  #           sum(:total_safiras)
  # end

  # def safiras_per(pr_id)
  #   self.rewards.find_by_professional_id(pr_id).try(:total_safiras) || 0
  # end

  # def future_schedules
  #   self.schedules.includes(:service).in_the_future
  # end

  def my_professionals
    self.professionals.where(status_id: Status.where("nome IN ('testando', 'assinante')")).distinct
  end

  # Sobrescrevendo método que ativa validações no e-mail
  # para que e-mail não seja obrigatório nos casos onde
  # cadastro é realizado com sistemas de terceiros.
  def email_required?
    super && provider.blank? && uid.blank?
  end

  # Sobrescrevendo método que ativa validações no password
  # para que password não seja obrigatório nos casos onde
  # cadastro é realizado com sistemas de terceiros.
  def password_required?
    super && provider.blank? && uid.blank?
  end
end

app/controllers/customers_controller.rb
class CustomersController < Devise::RegistrationsController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]
  layout 'customer/customer', only: [:minhas_safiras_por_profissionais]

  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    if invited?
      super
    else
      redirect_to root_path, flash: { error: 'Para cadastrar-se como cliente, você deve ser convidado. Caso tenha recebido o convite, certifique-se de acessar usando o link enviado para seu telefone.' }
    end
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    if invited?
      super
    else
      redirect_to :back, flash: { error: 'Não encontramos convite para os dados fornecidos.' }
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def minhas_safiras_por_profissionais
    @my_professionals = current_customer.customer_invitations.map(&:professional).uniq
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:email, :password, :password_confirmation, :schedule_invitation)
    end

    def invited?
      @sc = @token = nil
      if params[:s]
        @sc = params[:s][ 4...params[:s].size]
        @token = params[:s][0..3]
      else
        @sc = customer_params[:schedule_invitation]
        @token = params[:t]
      end

      CustomerInvitation.find_by_schedule_and_token(@sc, @token).present?
    end
end

app/helpers/customers_helper.rb
module CustomersHelper
  def customer_widget_title
    case controller_name
    when 'schedules'
      widget_title('scissors', 'Meus Profissionais e Serviços')
    when 'photo_logs'
      widget_title('camera', 'Enviar Fotos')
    when 'photo_log_steps'
      case params[:id]
      when 'comments'
       widget_title('camera', 'Enviar Fotos (Passo 2 de 3)')
      when 'professional_info'
        widget_title('camera', 'Enviar Fotos (Passo 3 de 3)')
      when 'revision'
        widget_title('camera', 'Enviar Fotos (Revisão...)')
      end
    end
  end

  def safiras
    @safiras ||= current_customer.safiras_somadas
  end

  def safiras_percentage_by(service_price)
    if service_price
      percentage = ( prof_safiras / ( service_price * 2 ) ) * 100
      percentage > 100 ? 100 : percentage
    end
  end

  def economia
    @economizados ||= format("%.2f", current_customer.schedules.safiras_resgatadas * 0.50)
  end

  def nome_cliente
    current_customer.try(:nome)
  end

  def prof_safiras(pr_id=nil)
    @safirasDoProf = (pr_id.present? ? current_customer.safiras_per(pr_id) : @safirasDoProf)
  end

  def enough_safiras?(service_preco)
    prof_safiras >= service_preco * 2
  end

  def insert_badge
    concat(
      content_tag(
        :div,
        {
          'class' => "col-xs-12 col-md-4 button-middle dica",
          'data-toggle' => "popover",
          'data-trigger' => "hover",
          'data-placement'=>"top",
          'data-html' => "true",
          'title' => "Parabéns!",
          'data-content' => "Você acumulou Safiras suficiente para trocar por este serviço.<br /><br />Para efetuar a troca, marque um horário com o profissional e diga a ele que utilize suas Safiras como pagamento."
        }
      ) do
        concat image_tag "badge.png"
      end
    )
  end
  
  private

  def widget_title(icon, text)
    concat content_tag :i, nil, class: "fa fa-#{icon}"
    concat " " + text
  end

end

app/views/layouts/customer/_footer.html.erb
<!-- Start footer content -->
<footer class="footer-content">
    2014 - <span id="copyright-year"></span> &copy; <%= link_to 'SafiraSaloes', customer_root_path %>
    <span class="pull-right">0.01 GB(0%) of 15 GB used</span>
</footer><!-- /.footer-content -->
<!--/ End footer content -->

app/views/layouts/customer/_main_content.html.erb
<!-- START @PAGE CONTENT -->
<section id="page-content">

    <!-- Start page header -->
    <div class="header-content">
        <h2><% customer_widget_title %> <!-- <span>Just-add-water CSS animations</span> --></h2>
        <!-- /.breadcrumb-wrapper
        <div class="breadcrumb-wrapper hidden-xs">
            <span class="label">You are here:</span>
            <ol class="breadcrumb">
                <li>
                    <i class="fa fa-home"></i>
                    <a href="dashboard.html">Dashboard</a>
                    <i class="fa fa-angle-right"></i>
                </li>
                <li class="active">Animate.css</li>
            </ol>
        </div> -->
    </div><!-- /.header-content -->
    <!--/ End page header -->

    <!-- Start body content -->
    <div class="body-content">

        <div class="row">
            <div class="col-md-12">

                <!-- Start animate.css -->
                <div class="panel rounded shadow">
                    <div class="panel-heading test">
                        <div class="pull-left">
                            <h3 class="panel-title"><% customer_widget_title %></h3>
                        </div>
                        <!--
                        <div class="pull-right">
                            <button title="" data-original-title="" class="btn btn-sm" data-action="collapse" data-container="body" data-toggle="tooltip" data-placement="top" data-title="Collapse"><i class="fa fa-angle-up"></i></button>
                            <button title="" data-original-title="" class="btn btn-sm" data-action="remove" data-container="body" data-toggle="tooltip" data-placement="top" data-title="Remove"><i class="fa fa-times"></i></button>
                        </div>-->
                        <div class="clearfix"></div>
                    </div><!-- /.panel-heading -->
                    <div class="panel-body">

                      <%= flash_messages %>
                      <%= yield %>

                    </div><!-- /.panel-body -->
                </div><!-- /.panel -->
                <!--/ End animate.css -->

            </div>
        </div>

    </div><!-- /.body-content -->
    <!--/ End body content -->

    <%# render "layouts/customer/footer" %>

</section><!-- /#page-content -->
<!--/ END PAGE CONTENT -->

app/views/layouts/customer/_main_header.html.erb
<!--START @HEADER -->
<header id="header">

    <!-- Start header left -->
    <div class="header-left">
        <!-- Start offcanvas left: This menu will take position at the top of template header (mobile only). Make sure that only #header have the `position: relative`, or it may cause unwanted behavior -->
        <div class="navbar-minimize-mobile left">
            <i class="fa fa-bars"></i>
        </div>
        <!--/ End offcanvas left -->

        <!-- Start navbar header -->
        <div class="navbar-header" style="background-color: #c4e2bb">

            <!-- Start brand -->
            <%= link_to '', class: "navbar-brand" do %>
                <%= image_tag "logo175x50.png", class: 'logo', alt: 'SafiraSalões' %>
            <% end %>
            
            <!--/ End brand -->

        </div><!-- /.navbar-header -->
        <!--/ End navbar header -->

        <!-- Start offcanvas right: This menu will take position at the top of template header (mobile only). Make sure that only #header have the `position: relative`, or it may cause unwanted behavior -->
        <!-- <div class="navbar-minimize-mobile right">
            <i class="fa fa-cog"></i>
        </div> -->
        <!--/ End offcanvas right -->

        <div class="clearfix"></div>
    </div><!-- /.header-left -->
    <!--/ End header left -->

    <!-- Start header right -->
    <div class="header-right">
        <!-- Start navbar toolbar -->
        <div class="navbar navbar-toolbar">

            <!-- Start left navigation -->
            <ul class="nav navbar-nav navbar-left">

                <!-- Start sidebar shrink -->
                <li class="navbar-minimize">
                    <a href="javascript:void(0);" title="Minimize sidebar">
                        <i class="fa fa-bars"></i>
                    </a>
                </li>
                <!--/ End sidebar shrink -->

            </ul><!-- /.navbar-left -->
            <!--/ End left navigation -->



        </div><!-- /.navbar-toolbar -->
        <!--/ End navbar toolbar -->
    </div><!-- /.header-right -->
    <!--/ End header left -->

</header> <!-- /#header -->
<!--/ END HEADER -->

app/views/layouts/customer/_secondary_header.html.erb
  <header>
    <div class="container">
      <div class="row">

        <!-- Logo section -->
        <div class="col-md-3">
          <!-- Logo. -->
          <div class="logo">
            <h1>
              <%= link_to customer_root_path do %>
                Safira<span class="bold">Salões</span>
              <% end %>
            </h1>
          </div>
          <!-- Logo ends -->
        </div>

        <!-- Button section -->
        <div class="col-md-5">

          <!-- Buttons -->
          <ul class="nav nav-pills">

            
          </ul>

        </div>

        <!-- Data section -->

        <div class="col-md-4">
          <div class="header-data">
            <!-- Traffic data -->
            <%= link_to customer_root_path do %>
              <div class="hdata">
                <div class="mcol-left">
                  <!-- Icon with red background -->
                  <i class="fa fa-diamond bred"></i> 
                </div>
                <div class="mcol-right">
                  <!-- Number of visitors -->
                  <p><%= safiras %> <em>Safiras</em></p>
                </div>
                <div class="clearfix"></div>
              </div>
            <% end %>

            <!-- revenue data -->
            <a href="#">
              <div class="hdata">
                <div class="mcol-left">
                  <!-- Icon with green background -->
                  <i class="fa fa-money bgreen"></i> 
                </div>
                <div class="mcol-right">
                  <!-- Number of visitors -->
                  <p><%= economia %><em>economizados</em></p>
                </div>
                <div class="clearfix"></div>
              </div>                        
            </a>
          </div>
        </div>

      </div>
    </div>
  </header>

app/views/layouts/customer/_sidebar.html.erb
<!--

START @SIDEBAR LEFT
|=========================================================================================================================|
|  TABLE OF CONTENTS (Apply to sidebar left class)                                                                        |
|=========================================================================================================================|
|  01. sidebar-box               |  Variant style sidebar left with box icon                                              |
|  02. sidebar-rounded           |  Variant style sidebar left with rounded icon                                          |
|  03. sidebar-circle            |  Variant style sidebar left with circle icon                                           |
|=========================================================================================================================|

-->
<aside id="sidebar-left" class="sidebar-circle">

    <!-- Start left navigation - profile shortcut -->
    <div class="sidebar-content">
        <div class="media">
            <a class="pull-left has-notif avatar">
                <% if current_customer.avatar_url.present? %>
                    <%= image_tag current_customer.avatar_url %>
                <% end %>
                <!-- <i class="online"></i> -->
            </a>
            <div class="media-body">
                <h4 class="media-heading"><%= "Olá, <span>#{current_customer.nome}</span>".html_safe if current_customer.nome.present? %></h4>
                <!-- <small>Web Designer</small> -->
            </div>
        </div>
    </div><!-- /.sidebar-content -->
    <!--/ End left navigation -  profile shortcut -->

    <!-- Start left navigation - menu -->
    <ul class="sidebar-menu">

        <!-- Start navigation - dashboard
        <li class="<%= active(['photo_logs', 'photo_log_steps']) %>">
          <%# link_to(new_photo_log_path, id: 'envio_fotos') do %>
            <span class="icon"><i class="fa fa-camera"></i></span>
            <span class="text">Enviar Fotos</span>
          <%# end %>
        </li>
         -->

        <li class="<%= active('schedules') %>">
          <%= link_to(customer_root_path, id: 'meus_servicos') do %>
            <span class="icon"><i class="fa fa-scissors"></i></span>
            <span class="text">Minhas Recompensas</span>
          <% end %>
        </li>
        <!--/ End navigation - dashboard -->

    </ul><!-- /.sidebar-menu -->
    <!--/ End left navigation - menu -->

    <!-- Start left navigation - footer -->
    <div class="sidebar-footer">
        <%= link_to destroy_session_path(current_resource), :method => :delete, id: "logout", 'data-url' => "page-lock-screen.html", class: "pull-left", style: "margin: 0% 30%;", 'data-toggle' => "tooltip", 'data-placement' => "top", 'data-title' => "Sair" do %>
          <i class="fa fa-power-off"></i> Sair
        <% end %>
    </div><!-- /.sidebar-footer -->
    <!--/ End left navigation - footer -->

</aside><!-- /#sidebar-left -->
<!--/ END SIDEBAR LEFT -->

app/views/layouts/customer/_woopra.html.erb
<!-- Start of Woopra Code -->
<script>
(function(){
        var t,i,e,n=window,o=document,a=arguments,s="script",r=["config","track","identify","visit","push","call","trackForm","trackClick"],c=function(){var t,i=this;for(i._e=[],t=0;r.length>t;t++)(function(t){i[t]=function(){return i._e.push([t].concat(Array.prototype.slice.call(arguments,0))),i}})(r[t])};for(n._w=n._w||{},t=0;a.length>t;t++)n._w[a[t]]=n[a[t]]=n[a[t]]||new c;i=o.createElement(s),i.async=1,i.src="//static.woopra.com/js/t/5.js",e=o.getElementsByTagName(s)[0],e.parentNode.insertBefore(i,e)
})("woopra");

woopra.config({
    domain: 'safirasaloes.com.br'
});

// Identify customer
woopra.identify({
    email: "<%= current_customer.email %>",
    name: "<%= current_customer.nome %>",
    user_type: 'customer',
    avatar: "<%= current_customer.avatar_url %>"
});
 
// track
woopra.track();
</script>
<!-- End of Woopra Code -->

app/views/layouts/customer/customer.html.erb
<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9"> <![endif]-->
<!--[if !IE]><!--> <html lang="en"> <!--<![endif]-->

    <!-- START @HEAD -->
    <head>
        <!-- START @META SECTION -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
        <title><%= ( title =  yield(:title) ).present? ? title : 'SafiraSaloes' %></title>
        <!--/ END META SECTION -->

        <!-- START @FAVICONS -->
        <!--<link href="../../../img/ico/apple-touch-icon-144x144-precomposed.png" rel="apple-touch-icon-precomposed" sizes="144x144">-->
        <!--<link href="../../../img/ico/apple-touch-icon-114x114-precomposed.png" rel="apple-touch-icon-precomposed" sizes="114x114">-->
        <!--<link href="../../../img/ico/apple-touch-icon-72x72-precomposed.png" rel="apple-touch-icon-precomposed" sizes="72x72">-->
        <!--<link href="../../../img/ico/apple-touch-icon-57x57-precomposed.png" rel="apple-touch-icon-precomposed">-->
        <!--<link href="../../../img/ico/apple-touch-icon.png" rel="shortcut icon">-->
        <%= favicon_link_tag      'favicon.png', rel: "shortcut icon" %>
        <!--/ END FAVICONS -->
        
        <!-- START @FONT STYLES -->
        <link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700" rel="stylesheet">
        <!--/ END FONT STYLES -->
        
        <%= stylesheet_link_tag   'application', media: 'all' %>
        <%= render "layouts/fb_pixel.html" if Rails.env.production? %>
        <%= render "layouts/hotjar.html" if Rails.env.production? %>
        <!-- Se profissional ainda não cadastrou informações de contato e não há errors na edição de suas informações, quer dizer
        que ele está acessando a tela de edição das informações de contato pela primeira vez. Logo, pixel do FB tem que ser carregado para contabilizar conversão  -->
        <%= render "layouts/customer/woopra.html" if Rails.env.production? %>
        <%= csrf_meta_tags %>

        <!-- START @IE SUPPORT -->
        <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
        <script src="../../../assets/global/plugins/bower_components/html5shiv/dist/html5shiv.min.js"></script>
        <script src="../../../assets/global/plugins/bower_components/respond-minmax/dest/respond.min.js"></script>
        <![endif]-->
        <!--/ END IE SUPPORT -->
    </head>
    <!--/ END HEAD -->

    <!--

    |=========================================================================================================================|
    |  TABLE OF CONTENTS (Use search to find needed section)                                                                  |
    |=========================================================================================================================|
    |  01. @HEAD                        |  Container for all the head elements                                                |
    |  02. @META SECTION                |  The meta tag provides metadata about the HTML document                             |
    |  03. @FAVICONS                    |  Short for favorite icon, shortcut icon, website icon, tab icon or bookmark icon    |
    |  04. @FONT STYLES                 |  Font from google fonts                                                             |
    |  05. @GLOBAL MANDATORY STYLES     |  The main 3rd party plugins css file                                                |
    |  06. @PAGE LEVEL STYLES           |  Specific 3rd party plugins css file                                                |
    |  07. @THEME STYLES                |  The main theme css file                                                            |
    |  08. @IE SUPPORT                  |  IE support of HTML5 elements and media queries                                     |
    |=========================================================================================================================|
    |  09. @BODY                        |  Contains all the contents of an HTML document                                      |
    |  10. @WRAPPER                     |  Wrapping page section                                                              |
    |  11. @HEADER                      |  Header page section contains about logo, top navigation, notification menu         |
    |  12. @SIDEBAR LEFT                |  Sidebar page section contains all sidebar menu left                                |
    |  13. @PAGE CONTENT                |  Contents page section contains breadcrumb, content page, footer page               |
    |  14. @SIDEBAR RIGHT               |  Sidebar page section contains all sidebar menu right                               |
    |  15. @BACK TOP                    |  Element back to top and action                                                     |
    |=========================================================================================================================|
    |  16. @CORE PLUGINS                |  The main 3rd party plugins script file                                             |
    |  17. @PAGE LEVEL PLUGINS          |  Specific 3rd party plugins script file                                             |
    |  18. @PAGE LEVEL SCRIPTS          |  The main theme script file                                                         |
    |=========================================================================================================================|

    START @BODY
    |=========================================================================================================================|
  |  TABLE OF CONTENTS (Apply to body class)                                                                                |
  |=========================================================================================================================|
    |  01. page-boxed                   |  Page into the box is not full width screen                                         |
  |  02. page-header-fixed            |  Header element become fixed position                                               |
  |  03. page-sidebar-fixed           |  Sidebar element become fixed position with scroll support                          |
  |  04. page-sidebar-minimize        |  Sidebar element become minimize style width sidebar                                |
  |  05. page-footer-fixed            |  Footer element become fixed position with scroll support on page content           |
  |  06. page-sound                   |  For playing sounds on user actions and page events                                 |
  |=========================================================================================================================|

  -->
    <body>

        <!--[if lt IE 9]>
        <p class="upgrade-browser">Oppsss!! Você está usando um navegador <strong>desatualizado</strong>. Por favor <a href="http://browsehappy.com/" target="_blank">atualize seu navegador</a> para melhor utilizar nosso sistema.</p>
        <![endif]-->

        <!-- START @WRAPPER -->
        <section id="wrapper">
          <%= render "layouts/customer/main_header" %>
          <div class="content">
            <%= render "layouts/customer/sidebar" %>
            <%= yield :modals %>
            <%= render "layouts/customer/main_content" %>
          </div>
          <%= javascript_include_tag 'application' %>
          <%# render "layouts/customer/webengage_professional" if Rails.env.production? %>
          <%# subscribe_to "/customer/order_exchanges/#{current_customer.id}" %>

        </section><!-- /#wrapper -->
        <!--/ END WRAPPER -->

        <!-- START @BACK TOP -->
        <div id="back-top" class="animated pulse circle">
            <i class="fa fa-angle-up"></i>
        </div><!-- /#back-top -->
        <!--/ END BACK TOP -->

    </body>
    <!--/ END BODY -->

</html>